
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felix
 */
public class Reg1 extends javax.swing.JFrame {

    /**
     * Creates new form Reg1
     */
    public Reg1() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Information");
        setPreferredSize(new java.awt.Dimension(430, 495));
        setResizable(false);
        setSize(new java.awt.Dimension(430, 495));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(430, 495));
        jPanel2.setPreferredSize(new java.awt.Dimension(430, 495));
        jPanel2.setLayout(null);

        jLabel1.setText("Patient ID:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(340, 70, 60, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("REGISTRATION FORM");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 20, 250, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(0, 2, 420, 0);

        jLabel10.setText("Occupation:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 320, 70, 16);

        jLabel9.setText("Phone Number:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 270, 90, 16);

        jLabel2.setText("Age:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(300, 160, 40, 16);

        jLabel5.setText("Sex:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 160, 30, 16);

        jLabel8.setText("Full Address:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 220, 80, 16);

        jLabel6.setText("Date of Birth:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 160, 80, 16);

        jLabel7.setText("Full Name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 100, 70, 16);

        jLabel4.setText("Reason for Consultation:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 370, 150, 16);

        jButton1.setText("<");
        jButton1.setMinimumSize(new java.awt.Dimension(10, 10));
        jButton1.setPreferredSize(new java.awt.Dimension(10, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 20, 50, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(340, 90, 60, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(90, 90, 110, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(250, 90, 60, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(50, 150, 50, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(190, 150, 100, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(340, 150, 60, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(110, 210, 290, 30);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(120, 260, 160, 30);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(100, 310, 180, 30);
        jPanel2.add(jTextField10);
        jTextField10.setBounds(170, 360, 230, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 0, 420, 2);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(260, 410, 73, 25);

        jButton5.setText("Next");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(340, 410, 60, 25);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(0, 60, 420, 2);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(0, 400, 420, 10);

        jLabel11.setText("Date:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(210, 100, 40, 16);

        jButton2.setText("Search");
        jButton2.setRolloverEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(330, 120, 80, 20);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(110, 410, 70, 25);

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(20, 410, 73, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
                h.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id = 0;
            String patient_full_name="",date_of_registration="",patient_sex="",date_of_birth="",patient_age="",
            patient_address="",patient_phone_number="",patient_occupation="",patient_reason_for_consultation="";
            
                patient_id = Integer.parseInt(jTextField1.getText());
            	patient_full_name = jTextField2.getText();
                date_of_registration = jTextField3.getText();
                patient_sex = jTextField4.getText();
                date_of_birth = jTextField5.getText();
                patient_age = jTextField6.getText();
                patient_address = jTextField7.getText();
                patient_phone_number = jTextField8.getText();
                patient_occupation = jTextField9.getText(); 
                patient_reason_for_consultation = jTextField10.getText(); 
                
                
            Statement stm = conn.createStatement();
            
            String mysql = "INSERT INTO patient_registration VALUES('"+patient_id+"','"+patient_full_name+"','"+date_of_registration+"','"+patient_sex+"','"+date_of_birth+"',"
                    + "'"+patient_age+"','"+patient_address+"','"+patient_phone_number+"','"+patient_occupation+"','"+patient_reason_for_consultation+"')";
            stm.execute(mysql);
            
            JOptionPane.showMessageDialog(null, "Record is successfully added");
            conn.close();
                            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Reg2 reg = new Reg2();
                reg.setVisible(true);
                this.dispose();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            int patient_id = Integer.parseInt(jTextField1.getText());
            
            Statement stm = conn.createStatement();
            String sqlsearch = ("SELECT * FROM patient_registration WHERE patient_id='"+patient_id+"'");
            ResultSet rs = stm.executeQuery(sqlsearch);
            
            if(rs.next()){
                jTextField2.setText(rs.getString("patient_full_name"));
                jTextField3.setText(rs.getString("date_of_registration"));
                jTextField4.setText(rs.getString("patient_sex"));
                jTextField5.setText(rs.getString("date_of_birth"));
                jTextField6.setText(rs.getString("patient_age"));
                jTextField7.setText(rs.getString("patient_address"));
                jTextField8.setText(rs.getString("patient_phone_number"));
                jTextField9.setText(rs.getString("patient_occupation"));
                jTextField10.setText(rs.getString("patient_reason_for_consultation"));
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id = 0;
            String patient_full_name="",date_of_registration="",patient_sex="",date_of_birth="",patient_age="",
            patient_address="",patient_phone_number="",patient_occupation="",patient_reason_for_consultation="";
            
                patient_id = Integer.parseInt(jTextField1.getText());
            	patient_full_name = jTextField2.getText();
                date_of_registration = jTextField3.getText();
                patient_sex = jTextField4.getText();
                date_of_birth = jTextField5.getText();
                patient_age = jTextField6.getText();
                patient_address = jTextField7.getText();
                patient_phone_number = jTextField8.getText();
                patient_occupation = jTextField9.getText(); 
                patient_reason_for_consultation = jTextField10.getText(); 
                
                Statement stm = conn.createStatement(); 
                stm.executeUpdate("UPDATE patient_registration SET patient_full_name = '"+patient_full_name+"',"
                        + "date_of_registration = '"+date_of_registration+"',patient_sex = '"+patient_sex+"',date_of_birth = '"+date_of_birth+"',patient_age = '"+patient_age+"',"
                                + "patient_address = '"+patient_address+"',patient_phone_number = '"+patient_phone_number+"',patient_occupation = '"+patient_occupation+"',"
                                        + "patient_reason_for_consultation = '"+patient_reason_for_consultation+"' WHERE patient_id='"+patient_id+"'");
            JOptionPane.showMessageDialog(null, "The record was updated.");
            conn.close();
                
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id = 0;
            
            patient_id = Integer.parseInt(jTextField1.getText());
            
            Statement stm = conn.createStatement();
            stm.executeUpdate("DELETE FROM patient_registration WHERE patient_id='"+patient_id+"'");
            
            JOptionPane.showMessageDialog(null, "A record was successfully deleted");
            conn.close();
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
