
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felix
 */
public class Reg4 extends javax.swing.JFrame {

    /**
     * Creates new form Reg2
     */
    
    public Reg4() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Helath Record");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(660, 895));
        setPreferredSize(new java.awt.Dimension(660, 895));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 895));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(660, 870));
        jPanel2.setPreferredSize(new java.awt.Dimension(660, 870));
        jPanel2.setLayout(null);

        jSeparator1.setToolTipText("");
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(-20, 0, 730, 10);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 52, 700, 10);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(0, 210, 660, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("FAMILY HEALTH HISTORY");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 210, 290, 50);

        jLabel2.setText("Temperature:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(470, 160, 90, 16);

        jLabel3.setText("Patient ID:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(440, 80, 70, 16);

        jLabel4.setText("Tubercolosis:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 580, 80, 16);

        jLabel5.setText("Sex:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 120, 30, 16);

        jLabel6.setText("Date of Birth:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 120, 80, 16);

        jLabel7.setText("Age:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(460, 120, 40, 16);

        jLabel8.setText("Height:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(30, 160, 50, 16);

        jLabel9.setText("Weight:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 160, 50, 16);

        jLabel10.setText("Blood Pressure:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(290, 160, 90, 16);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("PATIENT HEALTH RECORD");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(180, 0, 290, 50);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(0, 260, 660, 10);

        jLabel12.setText("Full Name:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(30, 80, 70, 16);

        jLabel13.setText("Lung Disease:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(460, 580, 90, 16);

        jLabel14.setText("Cancer:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(220, 300, 50, 16);

        jLabel15.setText("Heart Disease:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(410, 300, 90, 16);

        jLabel16.setText("Respiratory Disease:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 740, 130, 16);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(0, 420, 660, 10);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("PERSONAL HEALTH HISTORY");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(170, 420, 320, 50);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(0, 470, 660, 10);

        jLabel18.setText("Diabetes:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(30, 300, 60, 16);

        jLabel19.setText("Diabetes:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(30, 510, 60, 16);

        jLabel20.setText("Seizures:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(270, 740, 60, 16);

        jLabel21.setText("High Blood Pressure:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(30, 370, 120, 16);

        jLabel22.setText("Tubercolosis:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(320, 370, 80, 16);

        jLabel23.setText("Heart Disease:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(410, 510, 90, 16);

        jLabel24.setText("High Blood Pressure:");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(30, 580, 120, 16);

        jLabel25.setText("Mental Illness:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(30, 660, 90, 16);

        jLabel26.setText("Muscular Disease:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(230, 660, 110, 16);

        jLabel27.setText("Nervous Disorder:");
        jPanel2.add(jLabel27);
        jLabel27.setBounds(460, 740, 110, 10);

        jLabel28.setText("Cancer:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(210, 510, 60, 16);

        jLabel29.setText("Kidney Disease:");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(460, 660, 100, 16);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(100, 72, 330, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(510, 70, 50, 30);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(60, 110, 60, 30);
        jPanel2.add(jTextField4);
        jTextField4.setBounds(240, 110, 190, 30);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(500, 110, 40, 30);
        jPanel2.add(jTextField6);
        jTextField6.setBounds(80, 152, 70, 30);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(210, 150, 70, 30);
        jPanel2.add(jTextField8);
        jTextField8.setBounds(390, 150, 70, 30);
        jPanel2.add(jTextField9);
        jTextField9.setBounds(560, 152, 60, 30);

        jCheckBox1.setText("Yes");
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(100, 280, 50, 25);

        jCheckBox2.setText("No");
        jPanel2.add(jCheckBox2);
        jCheckBox2.setBounds(100, 310, 50, 25);

        jCheckBox3.setText("Yes");
        jPanel2.add(jCheckBox3);
        jCheckBox3.setBounds(280, 280, 49, 25);

        jCheckBox4.setText("No");
        jPanel2.add(jCheckBox4);
        jCheckBox4.setBounds(280, 310, 50, 25);

        jCheckBox5.setText("Yes");
        jPanel2.add(jCheckBox5);
        jCheckBox5.setBounds(510, 280, 49, 25);

        jCheckBox6.setText("No");
        jPanel2.add(jCheckBox6);
        jCheckBox6.setBounds(510, 310, 50, 25);

        jCheckBox7.setText("Yes");
        jPanel2.add(jCheckBox7);
        jCheckBox7.setBounds(160, 350, 49, 25);

        jCheckBox8.setText("No");
        jPanel2.add(jCheckBox8);
        jCheckBox8.setBounds(160, 380, 50, 25);

        jCheckBox9.setText("Yes");
        jPanel2.add(jCheckBox9);
        jCheckBox9.setBounds(410, 350, 49, 25);

        jCheckBox10.setText("No");
        jPanel2.add(jCheckBox10);
        jCheckBox10.setBounds(410, 380, 50, 25);

        jCheckBox11.setText("Yes");
        jPanel2.add(jCheckBox11);
        jCheckBox11.setBounds(90, 490, 49, 25);

        jCheckBox12.setText("No");
        jPanel2.add(jCheckBox12);
        jCheckBox12.setBounds(90, 520, 50, 25);

        jCheckBox13.setText("Yes");
        jPanel2.add(jCheckBox13);
        jCheckBox13.setBounds(270, 490, 49, 25);

        jCheckBox14.setText("No");
        jPanel2.add(jCheckBox14);
        jCheckBox14.setBounds(270, 520, 50, 25);

        jCheckBox15.setText("Yes");
        jPanel2.add(jCheckBox15);
        jCheckBox15.setBounds(500, 490, 49, 25);

        jCheckBox16.setText("No");
        jPanel2.add(jCheckBox16);
        jCheckBox16.setBounds(500, 520, 50, 25);

        jCheckBox17.setText("Yes");
        jPanel2.add(jCheckBox17);
        jCheckBox17.setBounds(160, 560, 50, 25);

        jCheckBox18.setText("No");
        jPanel2.add(jCheckBox18);
        jCheckBox18.setBounds(160, 590, 50, 25);

        jCheckBox19.setText("Yes");
        jPanel2.add(jCheckBox19);
        jCheckBox19.setBounds(350, 560, 49, 25);

        jCheckBox20.setText("No");
        jPanel2.add(jCheckBox20);
        jCheckBox20.setBounds(350, 590, 50, 25);

        jCheckBox21.setText("Yes");
        jPanel2.add(jCheckBox21);
        jCheckBox21.setBounds(550, 560, 49, 25);

        jCheckBox22.setText("No");
        jPanel2.add(jCheckBox22);
        jCheckBox22.setBounds(550, 590, 50, 25);

        jCheckBox23.setText("Yes");
        jPanel2.add(jCheckBox23);
        jCheckBox23.setBounds(120, 640, 49, 25);

        jCheckBox24.setText("No");
        jPanel2.add(jCheckBox24);
        jCheckBox24.setBounds(120, 670, 50, 25);

        jCheckBox25.setText("Yes");
        jPanel2.add(jCheckBox25);
        jCheckBox25.setBounds(350, 640, 49, 25);

        jCheckBox26.setText("No");
        jPanel2.add(jCheckBox26);
        jCheckBox26.setBounds(350, 670, 50, 25);

        jCheckBox27.setText("Yes");
        jPanel2.add(jCheckBox27);
        jCheckBox27.setBounds(560, 640, 49, 25);

        jCheckBox28.setText("No");
        jPanel2.add(jCheckBox28);
        jCheckBox28.setBounds(560, 670, 50, 25);

        jCheckBox29.setText("Yes");
        jPanel2.add(jCheckBox29);
        jCheckBox29.setBounds(160, 720, 49, 25);

        jCheckBox30.setText("No");
        jPanel2.add(jCheckBox30);
        jCheckBox30.setBounds(160, 750, 50, 25);

        jCheckBox31.setText("Yes");
        jPanel2.add(jCheckBox31);
        jCheckBox31.setBounds(340, 720, 49, 25);

        jCheckBox32.setText("No");
        jPanel2.add(jCheckBox32);
        jCheckBox32.setBounds(340, 750, 50, 25);

        jCheckBox33.setText("Yes");
        jPanel2.add(jCheckBox33);
        jCheckBox33.setBounds(570, 720, 49, 25);

        jCheckBox34.setText("No");
        jPanel2.add(jCheckBox34);
        jCheckBox34.setBounds(570, 750, 50, 25);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 10, 50, 25);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(570, 810, 57, 25);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(480, 810, 73, 25);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(0, 790, 670, 2);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(560, 70, 70, 30);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(20, 810, 73, 25);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(110, 810, 69, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 670, 880);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reg3 reg = new Reg3();
                reg.setVisible(true);
                this.dispose();
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Reg5 reg = new Reg5();
                reg.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id=0;
            String patient_full_name="",patient_sex="",	date_of_birth="",patient_age="",patient_height="",patient_weight="",patient_bp="",patient_temp="",
                    diabetes="",cancer="",heart_disease="",high_blood_pressure="",tubercolosis="",p_diabetes="",p_cancer="",p_heart_disease="",p_high_blood_pressure="",
                    p_tubercolosis="",p_lung_disease="",p_mental_illness="",p_muscular_disease="",p_kidney_disease="",p_respiratory_disease="",
                    p_seizures="",p_nervous_disorder="";
            
                    patient_id = Integer.parseInt(jTextField2.getText());
                    patient_full_name = jTextField1.getText();
                    patient_sex = jTextField3.getText();
                    date_of_birth = jTextField4.getText();
                    patient_age = jTextField5.getText();
                    patient_height = jTextField6.getText();
                    patient_weight = jTextField7.getText();
                    patient_bp = jTextField8.getText(); 
                    patient_temp = jTextField9.getText();
                    
                    if(jCheckBox1.isSelected()){
                    diabetes = "Yes";
                    }if(jCheckBox2.isSelected()){
                    diabetes = "No";
                    }
                    
                    if(jCheckBox3.isSelected()){
                    cancer = "Yes";
                    }if(jCheckBox4.isSelected()){
                    cancer = "No";
                    }
                    
                    if(jCheckBox5.isSelected()){
                    heart_disease = "Yes";
                    }if(jCheckBox6.isSelected()){
                    heart_disease = "No";
                    }
                    
                    if(jCheckBox7.isSelected()){
                    high_blood_pressure = "Yes";
                    }if(jCheckBox8.isSelected()){
                    high_blood_pressure = "No";
                    }
                    
                    if(jCheckBox9.isSelected()){
                    tubercolosis = "Yes";
                    }if(jCheckBox10.isSelected()){
                    tubercolosis = "No";
                    }
                    
                    if(jCheckBox11.isSelected()){
                    p_diabetes = "Yes";
                    }if(jCheckBox12.isSelected()){
                    p_diabetes = "No";
                    }
                    
                    if(jCheckBox13.isSelected()){
                    p_cancer = "Yes";
                    }if(jCheckBox14.isSelected()){
                    p_cancer = "No";
                    }
                    
                    if(jCheckBox15.isSelected()){
                    p_heart_disease = "Yes";
                    }if(jCheckBox16.isSelected()){
                    p_heart_disease = "No";
                    }
                    
                    if(jCheckBox17.isSelected()){
                    p_high_blood_pressure = "Yes";
                    }if(jCheckBox18.isSelected()){
                    p_high_blood_pressure = "No";
                    }
                    
                    if(jCheckBox19.isSelected()){
                    p_tubercolosis = "Yes";
                    }if(jCheckBox20.isSelected()){
                    p_tubercolosis = "No";
                    }
                    
                    if(jCheckBox21.isSelected()){
                    p_lung_disease = "Yes";
                    }if(jCheckBox22.isSelected()){
                    p_lung_disease = "No";
                    }
                    
                    if(jCheckBox23.isSelected()){
                    p_mental_illness = "Yes";
                    }if(jCheckBox24.isSelected()){
                    p_mental_illness = "No";
                    }
                    
                    if(jCheckBox25.isSelected()){
                    p_muscular_disease = "Yes";
                    }if(jCheckBox26.isSelected()){
                    p_muscular_disease = "No";
                    }
                    
                    if(jCheckBox27.isSelected()){
                    p_kidney_disease = "Yes";
                    }if(jCheckBox28.isSelected()){
                    p_kidney_disease = "No";
                    }
                    
                    if(jCheckBox29.isSelected()){
                    p_respiratory_disease = "Yes";
                    }if(jCheckBox30.isSelected()){
                    p_respiratory_disease = "No";
                    }
                    
                    if(jCheckBox31.isSelected()){
                    p_seizures = "Yes";
                    }if(jCheckBox32.isSelected()){
                    p_seizures = "No";
                    }
                    
                    if(jCheckBox33.isSelected()){
                    p_nervous_disorder = "Yes";
                    }if(jCheckBox34.isSelected()){
                    p_nervous_disorder = "No";
                    }
                    
                    Statement stm = conn.createStatement();
                        String mysql = "INSERT INTO patient_health_record VALUES('"+patient_id+"','"+patient_full_name+"','"+patient_sex+"','"+date_of_birth+"',"
                                + "'"+patient_age+"','"+patient_height+"','"+patient_weight+"','"+patient_bp+"','"+patient_temp+"','"+diabetes+"','"+cancer+"',"
                                + "'"+heart_disease+"','"+high_blood_pressure+"','"+tubercolosis+"','"+	p_diabetes+"','"+p_cancer+"','"+p_heart_disease+"','"+p_high_blood_pressure+"',"
                                + "'"+p_tubercolosis+"','"+p_lung_disease+"','"+p_mental_illness+"','"+p_muscular_disease+"','"+p_kidney_disease+"','"+p_respiratory_disease+"',"
                                + "'"+p_seizures+"','"+p_nervous_disorder+"')";
                                
                        stm.execute(mysql);
                        
                        JOptionPane.showMessageDialog(null, "Record is successfully added");
                        conn.close();
           
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id = Integer.parseInt(jTextField2.getText()); 
            Statement stm = conn.createStatement();
            String sqlsearch = ("SELECT * FROM patient_health_record WHERE patient_id='"+patient_id+"'");
            ResultSet rs = stm.executeQuery(sqlsearch);
            
            if(rs.next()){
                jTextField1.setText(rs.getString("patient_full_name"));
                jTextField3.setText(rs.getString("patient_sex"));
                jTextField4.setText(rs.getString("date_of_birth"));
                jTextField5.setText(rs.getString("patient_age"));
                jTextField6.setText(rs.getString("patient_height"));
                jTextField7.setText(rs.getString("patient_weight"));
                jTextField8.setText(rs.getString("patient_bp"));
                jTextField9.setText(rs.getString("patient_temp"));
                
                if(rs.getString("diabetes").equals("Yes")){
                    jCheckBox1.setSelected(true);
                    jCheckBox2.setSelected(false);
                }if(rs.getString("diabetes").equals("No")){
                    jCheckBox2.setSelected(true);
                    jCheckBox1.setSelected(false);
                }
                
                if(rs.getString("cancer").equals("Yes")){
                    jCheckBox3.setSelected(true);
                    jCheckBox4.setSelected(false);
                }if(rs.getString("cancer").equals("No")){
                    jCheckBox4.setSelected(true);
                    jCheckBox3.setSelected(false);
                }
                
                if(rs.getString("heart_disease").equals("Yes")){
                    jCheckBox5.setSelected(true);
                    jCheckBox6.setSelected(false);
                }if(rs.getString("heart_disease").equals("No")){
                    jCheckBox6.setSelected(true);
                    jCheckBox5.setSelected(false);
                }
                
                if(rs.getString("high_blood_pressure").equals("Yes")){
                    jCheckBox7.setSelected(true);
                    jCheckBox8.setSelected(false);
                }if(rs.getString("high_blood_pressure").equals("No")){
                    jCheckBox8.setSelected(true);
                    jCheckBox7.setSelected(false);
                }
                
                if(rs.getString("tubercolosis").equals("Yes")){
                    jCheckBox9.setSelected(true);
                    jCheckBox10.setSelected(false);
                }if(rs.getString("tubercolosis").equals("No")){
                    jCheckBox10.setSelected(true);
                    jCheckBox9.setSelected(false);
                }
                
                if(rs.getString("p_diabetes").equals("Yes")){
                    jCheckBox11.setSelected(true);
                    jCheckBox12.setSelected(false);
                }if(rs.getString("p_diabetes").equals("No")){
                    jCheckBox12.setSelected(true);
                    jCheckBox11.setSelected(false);
                }
                
                if(rs.getString("p_cancer").equals("Yes")){
                    jCheckBox13.setSelected(true);
                    jCheckBox14.setSelected(false);
                }if(rs.getString("p_cancer").equals("No")){
                    jCheckBox14.setSelected(true);
                    jCheckBox13.setSelected(false);
                }
                
                if(rs.getString("p_heart_disease").equals("Yes")){
                    jCheckBox15.setSelected(true);
                    jCheckBox16.setSelected(false);
                }if(rs.getString("p_heart_disease").equals("No")){
                    jCheckBox16.setSelected(true);
                    jCheckBox15.setSelected(false);
                }
                
                if(rs.getString("p_high_blood_pressure").equals("Yes")){
                    jCheckBox17.setSelected(true);
                    jCheckBox18.setSelected(false);
                }if(rs.getString("p_high_blood_pressure").equals("No")){
                    jCheckBox18.setSelected(true);
                    jCheckBox17.setSelected(false);
                }
                
                if(rs.getString("p_tubercolosis").equals("Yes")){
                    jCheckBox19.setSelected(true);
                    jCheckBox20.setSelected(false);
                }if(rs.getString("p_tubercolosis").equals("No")){
                    jCheckBox20.setSelected(true);
                    jCheckBox19.setSelected(false);
                }
                
                if(rs.getString("p_lung_disease").equals("Yes")){
                    jCheckBox21.setSelected(true);
                    jCheckBox22.setSelected(false);
                }if(rs.getString("p_lung_disease").equals("No")){
                    jCheckBox22.setSelected(true);
                    jCheckBox21.setSelected(false);
                }
                
                if(rs.getString("p_mental_illness").equals("Yes")){
                    jCheckBox23.setSelected(true);
                    jCheckBox24.setSelected(false);
                }if(rs.getString("p_mental_illness").equals("No")){
                    jCheckBox24.setSelected(true);
                    jCheckBox23.setSelected(false);
                }
                
                if(rs.getString("p_muscular_disease").equals("Yes")){
                    jCheckBox25.setSelected(true);
                    jCheckBox26.setSelected(false);
                }if(rs.getString("p_muscular_disease").equals("No")){
                    jCheckBox26.setSelected(true);
                    jCheckBox25.setSelected(false);
                }
                
                if(rs.getString("p_kidney_disease").equals("Yes")){
                    jCheckBox27.setSelected(true);
                    jCheckBox28.setSelected(false);
                }if(rs.getString("p_kidney_disease").equals("No")){
                    jCheckBox28.setSelected(true);
                    jCheckBox27.setSelected(false);
                }
                
                if(rs.getString("p_respiratory_disease").equals("Yes")){
                    jCheckBox29.setSelected(true);
                    jCheckBox30.setSelected(false);
                }if(rs.getString("p_respiratory_disease").equals("No")){
                    jCheckBox30.setSelected(true);
                    jCheckBox29.setSelected(false);
                }
                
                if(rs.getString("p_seizures").equals("Yes")){
                    jCheckBox31.setSelected(true);
                    jCheckBox32.setSelected(false);
                }if(rs.getString("p_seizures").equals("No")){
                    jCheckBox32.setSelected(true);
                    jCheckBox31.setSelected(false);
                }
                
                if(rs.getString("p_nervous_disorder").equals("Yes")){
                    jCheckBox33.setSelected(true);
                    jCheckBox34.setSelected(false);
                }if(rs.getString("p_nervous_disorder").equals("No")){
                    jCheckBox34.setSelected(true);
                    jCheckBox33.setSelected(false);
                }
                
            }
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id=0;
            String patient_full_name="",patient_sex="",	date_of_birth="",patient_age="",patient_height="",patient_weight="",patient_bp="",patient_temp="",
                    diabetes="",cancer="",heart_disease="",high_blood_pressure="",tubercolosis="",p_diabetes="",p_cancer="",p_heart_disease="",p_high_blood_pressure="",
                    p_tubercolosis="",p_lung_disease="",p_mental_illness="",p_muscular_disease="",p_kidney_disease="",p_respiratory_disease="",
                    p_seizures="",p_nervous_disorder="";
            
            patient_id = Integer.parseInt(jTextField2.getText());
                    patient_full_name = jTextField1.getText();
                    patient_sex = jTextField3.getText();
                    date_of_birth = jTextField4.getText();
                    patient_age = jTextField5.getText();
                    patient_height = jTextField6.getText();
                    patient_weight = jTextField7.getText();
                    patient_bp = jTextField8.getText(); 
                    patient_temp = jTextField9.getText();
                    
                    if(jCheckBox1.isSelected()){
                    diabetes = "Yes";
                    }if(jCheckBox2.isSelected()){
                    diabetes = "No";
                    }
                    
                    if(jCheckBox3.isSelected()){
                    cancer = "Yes";
                    }if(jCheckBox4.isSelected()){
                    cancer = "No";
                    }
                    
                    if(jCheckBox5.isSelected()){
                    heart_disease = "Yes";
                    }if(jCheckBox6.isSelected()){
                    heart_disease = "No";
                    }
                    
                    if(jCheckBox7.isSelected()){
                    high_blood_pressure = "Yes";
                    }if(jCheckBox8.isSelected()){
                    high_blood_pressure = "No";
                    }
                    
                    if(jCheckBox9.isSelected()){
                    tubercolosis = "Yes";
                    }if(jCheckBox10.isSelected()){
                    tubercolosis = "No";
                    }
                    
                    if(jCheckBox11.isSelected()){
                    p_diabetes = "Yes";
                    }if(jCheckBox12.isSelected()){
                    p_diabetes = "No";
                    }
                    
                    if(jCheckBox13.isSelected()){
                    p_cancer = "Yes";
                    }if(jCheckBox14.isSelected()){
                    p_cancer = "No";
                    }
                    
                    if(jCheckBox15.isSelected()){
                    p_heart_disease = "Yes";
                    }if(jCheckBox16.isSelected()){
                    p_heart_disease = "No";
                    }
                    
                    if(jCheckBox17.isSelected()){
                    p_high_blood_pressure = "Yes";
                    }if(jCheckBox18.isSelected()){
                    p_high_blood_pressure = "No";
                    }
                    
                    if(jCheckBox19.isSelected()){
                    p_tubercolosis = "Yes";
                    }if(jCheckBox20.isSelected()){
                    p_tubercolosis = "No";
                    }
                    
                    if(jCheckBox21.isSelected()){
                    p_lung_disease = "Yes";
                    }if(jCheckBox22.isSelected()){
                    p_lung_disease = "No";
                    }
                    
                    if(jCheckBox23.isSelected()){
                    p_mental_illness = "Yes";
                    }if(jCheckBox24.isSelected()){
                    p_mental_illness = "No";
                    }
                    
                    if(jCheckBox25.isSelected()){
                    p_muscular_disease = "Yes";
                    }if(jCheckBox26.isSelected()){
                    p_muscular_disease = "No";
                    }
                    
                    if(jCheckBox27.isSelected()){
                    p_kidney_disease = "Yes";
                    }if(jCheckBox28.isSelected()){
                    p_kidney_disease = "No";
                    }
                    
                    if(jCheckBox29.isSelected()){
                    p_respiratory_disease = "Yes";
                    }if(jCheckBox30.isSelected()){
                    p_respiratory_disease = "No";
                    }
                    
                    if(jCheckBox31.isSelected()){
                    p_seizures = "Yes";
                    }if(jCheckBox32.isSelected()){
                    p_seizures = "No";
                    }
                    
                    if(jCheckBox33.isSelected()){
                    p_nervous_disorder = "Yes";
                    }if(jCheckBox34.isSelected()){
                    p_nervous_disorder = "No";
                    }
                                       
                    Statement stm = conn.createStatement();
                    stm.executeUpdate("UPDATE patient_health_record SET patient_full_name='"+patient_full_name+"',patient_sex='"+patient_sex+"',date_of_birth='"+date_of_birth+"',patient_age='"+patient_age+"',"
                            + "patient_height='"+patient_height+"',patient_weight='"+patient_weight+"',patient_bp='"+patient_bp+"',patient_temp='"+patient_temp+"',"
                            + "diabetes='"+diabetes+"',cancer='"+cancer+"',heart_disease='"+heart_disease+"',high_blood_pressure='"+high_blood_pressure+"',"
                            + "tubercolosis='"+tubercolosis+"',p_diabetes='"+p_diabetes+"',p_cancer='"+p_cancer+"',p_heart_disease='"+p_heart_disease+"',"
                            + "p_high_blood_pressure='"+p_high_blood_pressure+"',p_tubercolosis='"+p_tubercolosis+"',p_lung_disease='"+p_lung_disease+"',p_mental_illness='"+p_mental_illness+"',"
                            + "p_muscular_disease='"+p_muscular_disease+"',p_kidney_disease='"+p_kidney_disease+"',p_respiratory_disease='"+p_respiratory_disease+"',p_seizures='"+p_seizures+"',"
                            + "p_nervous_disorder='"+p_nervous_disorder+"' WHERE patient_id='"+patient_id+"'");
                    JOptionPane.showMessageDialog(null, "The record was updated.");
                    conn.close();
                    
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int patient_id = 0;
            
            patient_id = Integer.parseInt(jTextField2.getText());
            
            Statement stm = conn.createStatement();
            stm.executeUpdate("DELETE FROM patient_health_record WHERE patient_id='"+patient_id+"'");
            
            JOptionPane.showMessageDialog(null, "A record was successfully deleted");
            conn.close();
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}


//BOSS FILOK