
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author felix
 */
public class Reg5 extends javax.swing.JFrame {

    /**
     * Creates new form Reg5
     */
    public Reg5() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 315));
        setPreferredSize(new java.awt.Dimension(400, 315));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 50, 410, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 0, 410, 10);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CLINIC DOCTOR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 0, 180, 50);

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 10, 50, 25);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 222, 400, 10);

        jButton2.setText("Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 230, 79, 25);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(210, 230, 73, 25);

        jLabel2.setText("Doctor Name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 90, 80, 16);

        jLabel3.setText("Doctor ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 90, 60, 16);

        jLabel4.setText("Patient Records  ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 120, 16);

        jLabel5.setText("Patient ID:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 170, 60, 16);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 82, 120, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(320, 80, 50, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(150, 160, 50, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(320, 160, 50, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(300, 120, 69, 20);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 230, 73, 25);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(100, 230, 79, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Reg4 reg = new Reg4();
                reg.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int doctor_id,patient_recordsID,patient_id = 0;
            String doctor_name = "";
            
            doctor_name = jTextField1.getText();
            doctor_id = Integer.parseInt(jTextField2.getText());
            patient_recordsID = Integer.parseInt(jTextField3.getText());
            patient_id = Integer.parseInt(jTextField4.getText());
            
            Statement stm = conn.createStatement();
            
            String mysql = "INSERT INTO clinic_doctor VALUES('"+doctor_id+"','"+doctor_name+"','"+patient_recordsID+"','"+patient_id+"')";
            stm.execute(mysql);
                            
            JOptionPane.showMessageDialog(null, "Record is successfully added");
            conn.close();
            
        }catch (Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "All record has been added" + "\n"
                + "Return to Home?");
        
        Home h = new Home();
                h.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int doctor_id = Integer.parseInt(jTextField2.getText());
            
            Statement stm = conn.createStatement();
            String sqlsearch = ("SELECT * FROM clinic_doctor WHERE doctor_id='"+doctor_id+"'");
            ResultSet rs = stm.executeQuery(sqlsearch);
            
            if(rs.next()){
                jTextField1.setText(rs.getString("doctor_name"));
                jTextField3.setText(rs.getString("patient_recordsID"));
                jTextField4.setText(rs.getString("patient_id"));
            } 
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int doctor_id = 0;
            
            doctor_id = Integer.parseInt(jTextField2.getText());
            
            Statement stm = conn.createStatement();
            stm.executeUpdate("DELETE FROM clinic_doctor WHERE doctor_id='"+doctor_id+"'");
            
            JOptionPane.showMessageDialog(null, "A record was successfully deleted");
            conn.close();
                    
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sanford_world_clinic_db", "root", "");
            
            int doctor_id,patient_recordsID,patient_id = 0;
            String doctor_name = "";
            
            doctor_name = jTextField1.getText();
            doctor_id = Integer.parseInt(jTextField2.getText());
            patient_recordsID = Integer.parseInt(jTextField3.getText());
            patient_id = Integer.parseInt(jTextField4.getText());
            
            Statement stm = conn.createStatement();
            stm.executeUpdate("UPDATE clinic_doctor SET doctor_name='"+doctor_name+"' WHERE doctor_id='"+doctor_id+"'");
            JOptionPane.showMessageDialog(null, "The record was updated.");
            conn.close();
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reg5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reg5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
